spring.data.elasticsearch.clustername : es6.2
spring.data.elasticsearch.cluster-nodes : 192.168.74.1:9300,192.168.74.1:9500


spring.datasource.url: jdbc:mysql://localhost:3306/demo
spring.datasource.password: 123456
spring.datasource.username: root
spring.datasource.driver-class-name : com.mysql.cj.jdbc.Driver
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource

mybatis.mapper-locations: classpath:mapping/*.xml


spring.redis.cluster.nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
spring.redis.database: 0
spring.redis.jedis.pool.max-active: 8
spring.redis.jedis.pool.max-idle: 8
spring.redis.jedis.pool.max-wait: -1
spring.redis.jedis.pool.min-idle: 0
spring.redis.timeout: 3000
spring.redis.password:
spring.redis.maxAttempts : 10


